table F_Vendas
	lineageTag: 85d7c4ec-ba6f-40ba-b0e6-14b74d0db17b

	measure 'R$ Faturamento' = COALESCE(SUM(F_Vendas[Total]), 0)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: _Medidas
		lineageTag: f985698c-5689-4f8c-acc2-c221bb11435b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Lucro Liquido' = SUM(F_Vendas[Lucro Liquido]) + 0
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: _Medidas
		lineageTag: 7c0b7c81-bc0b-4dfb-97f0-eb5a2954989b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Faturamento Mes Anterior' = ```
			
			    CALCULATE(
			        [R$ Faturamento],
			        PREVIOUSMONTH(D_Calendario[Date])
			    )  
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: _Medidas
		lineageTag: c23305a4-81e4-4773-bc90-cc70fe1bc526

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Lucro Liquido Mes Anterior' = ```
			
			    CALCULATE(
			        [R$ Lucro Liquido],
			        PREVIOUSMONTH(D_Calendario[Date])
			    )  
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: _Medidas
		lineageTag: f570db80-df70-43f1-8fbd-9578b33861c6

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '% Variacao Faturamento' = ```
			
			    DIVIDE(
			        [R$ Faturamento], 
			        [R$ Faturamento Mes Anterior], 
			        0
			    ) - 1
			```
		displayFolder: _Medidas
		lineageTag: e07e610e-9dac-4096-9761-63addf0496b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Variacao Lucro Liquido' = ```
			
			    DIVIDE(
			        [R$ Lucro Liquido], 
			        [R$ Lucro Liquido Mes Anterior], 
			        0
			    ) - 1
			```
		displayFolder: _Medidas
		lineageTag: 98ed86a6-ecdb-4089-94d6-b19803e1c1c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Invoice ID'
		dataType: string
		lineageTag: 964f3b17-b680-4515-89d7-380f818b4eaf
		summarizeBy: none
		sourceColumn: Invoice ID

		annotation SummarizationSetBy = Automatic

	column Branch
		dataType: string
		lineageTag: 786c6f6f-a104-4960-8a9d-609184cd70a0
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 6ee70863-c08b-45e7-9343-5390311cbb5f
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'Customer type'
		dataType: string
		lineageTag: fdaa083d-466b-4b75-b9d0-b257cf40f9ba
		summarizeBy: none
		sourceColumn: Customer type

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 98342288-0036-4a69-82dd-55f81e3f5fb9
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Product line'
		dataType: string
		lineageTag: e900b230-d6c7-4da7-bc36-27945963f44c
		summarizeBy: none
		sourceColumn: Product line

		annotation SummarizationSetBy = Automatic

	column 'Unit price'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 2b20483a-7a8a-4c79-91e0-30df5d241d2f
		summarizeBy: sum
		sourceColumn: Unit price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 12aa4b19-9b70-4a5e-8af5-1b3ab7286d5c
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Tax 5%'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 9ed537e9-d62e-4f49-be56-44dd582b0cc1
		summarizeBy: sum
		sourceColumn: Tax 5%

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Total
		dataType: decimal
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 19316625-5880-4db1-b880-cfb20b6940d3
		summarizeBy: sum
		sourceColumn: Total

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: cb2d8b8e-f11e-44ed-8c10-664369a00a69
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Payment
		dataType: string
		lineageTag: 05c0cdc9-a628-4c0b-b75f-5c8386d6eecb
		summarizeBy: none
		sourceColumn: Payment

		annotation SummarizationSetBy = Automatic

	column cogs
		dataType: decimal
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: cc84978a-7d3a-458a-85c7-3cbf3ea36940
		summarizeBy: sum
		sourceColumn: cogs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Rating
		dataType: int64
		formatString: 0
		lineageTag: a8968c92-6b72-44a4-b794-c8a1cc32c9d2
		summarizeBy: sum
		sourceColumn: Rating

		annotation SummarizationSetBy = Automatic

	column DataFormatada
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9c4ecb0d-65eb-4ac6-b3a1-2adbfb1b9c66
		summarizeBy: none
		sourceColumn: DataFormatada

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Lucro Liquido' = [Total] - [cogs]
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 0a426663-c313-4195-a449-52fe6ace87ee
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition F_Vendas = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\Diego Neves\Documents\GitHub\PowerBI-Brasil\01 - Supermercado\Data\VENDAS.xlsx"), null, true),
				    supermarket_sales_Sheet = Fonte{[Item="supermarket_sales",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(supermarket_sales_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Invoice ID", type text}, {"Branch", type text}, {"City", type text}, {"Customer type", type text}, {"Gender", type text}, {"Product line", type text}, {"Unit price", Currency.Type}, {"Quantity", Int64.Type}, {"Tax 5%", Currency.Type}, {"Total", Int64.Type}, {"Time", type time}, {"Payment", type text}, {"cogs", Currency.Type}, {"Rating", Int64.Type}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "DataFormatada", each Text.Middle([Date], 0,2)),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Personalização Adicionada",{"DataFormatada"}),
				    #"Texto Inserido Antes do Delimitador" = Table.AddColumn(#"Colunas Removidas", "Mês", each Text.BeforeDelimiter([Date], "/"), type text),
				    #"Texto Inserido Entre os Delimitadores" = Table.AddColumn(#"Texto Inserido Antes do Delimitador", "Dia", each Text.BetweenDelimiters([Date], "/", "/"), type text),
				    #"Texto Inserido Após o Delimitador" = Table.AddColumn(#"Texto Inserido Entre os Delimitadores", "Ano", each Text.AfterDelimiter([Date], "/", {0, RelativePosition.FromEnd}), type text),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Texto Inserido Após o Delimitador", "DataFormatada", each Text.Combine({[Dia], "/", [Mês], "/", [Ano]})),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"DataFormatada", type date}}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Tipo Alterado1",{"Date", "Mês", "Dia", "Ano"})
				in
				    #"Colunas Removidas1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

